$kind: http-request
url: "{{baseUrl}}/inventory/"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "product_id": 1,
      "current_stock": 50,
      "minimum_stock_level": 5,
      "maximum_stock_level": 200
    }
order: 1000
