"""align database schema

Revision ID: 980a3e4eaf43
Revises: afed22aa68a4
Create Date: 2026-08-16 15:36:45.897009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980a3e4eaf43'
down_revision: Union[str, Sequence[str], None] = 'afed22aa68a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_constraint(op.f('uq_inventory_product_id'), 'inventory', type_='unique')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=True)
    op.create_index('ix_inventory_low_stock', 'inventory', ['current_stock', 'minimum_stock_level'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_column('notifications', 'read_at')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.create_index('ix_order_items_order_product', 'order_items', ['order_id', 'product_id'], unique=False)
    op.create_index('ix_orders_customer_status', 'orders', ['customer_id', 'status'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.drop_constraint(op.f('uq_payment_order_id'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.add_column('products', sa.Column('image', sa.Text(), nullable=True))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index('ix_products_price_status', 'products', ['price', 'status'], unique=False)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'updated_at')
    op.alter_column('reviews', 'review',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index('ix_reviews_product_created_at', 'reviews', ['product_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('reviews_order_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_customer_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_customer_id_fkey'), 'reviews', 'users', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('reviews_order_id_fkey'), 'reviews', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_reviews_product_created_at', table_name='reviews')
    op.alter_column('reviews', 'review',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_products_price_status', table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.alter_column('products', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('products', 'image')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('uq_payment_order_id'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index('ix_orders_customer_status', table_name='orders')
    op.drop_index('ix_order_items_order_product', table_name='order_items')
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_inventory_low_stock', table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_unique_constraint(op.f('uq_inventory_product_id'), 'inventory', ['product_id'], postgresql_nulls_not_distinct=False)
    op.add_column('categories', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###